#!/usr/bin/env python3
"""Generate Sources/tgapi/UI/EmbeddedLangs.h from Mx.bundle/*.lproj.

The previous version re-escaped every value it read:

    val = val.strip('";')
    val = val.replace('"', '\\"')

A .strings file already stores an inner quote escaped, as \", so that turned
\" into \\", which a compiler reads as "literal backslash, then end of
string". Everything after it was parsed as code, producing:

    error: expected '}' or ','                 (on the value itself)
    error: expected identifier or '('          (on each following language)
    error: extraneous closing brace ('}')      (at the end of the file)

The strip('";') was a second, latent bug: it removes any trailing run of
quote and semicolon characters, so a value ending in \" lost the escaped
quote as well and left a dangling backslash.

.strings and Objective-C string literals use the same escape syntax, so the
correct handling is to parse the escapes and pass the value through
unchanged. Nothing is re-escaped here.
"""

import argparse
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_BUNDLE = os.path.join(SCRIPT_DIR, "Mx.bundle")
DEFAULT_OUTPUT = os.path.join(SCRIPT_DIR, "Sources", "tgapi", "UI", "EmbeddedLangs.h")

# "key" = "value";  where either side may contain escaped characters.
# (?:[^"\\]|\\.)* treats a backslash plus the character after it as one unit,
# so an escaped quote inside the value does not end the match early.
ENTRY_RE = re.compile(r'^\s*"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;\s*$')


def c_string_is_balanced(value):
    """Scan a value the way a compiler scans the body of a string literal.

    Catches an unescaped quote (which would end the literal early) and a
    trailing backslash (which would escape the closing quote).
    """
    i = 0
    while i < len(value):
        if value[i] == "\\":
            if i + 1 >= len(value):
                return False  # dangling backslash
            i += 2
            continue
        if value[i] == '"':
            return False  # unescaped quote
        i += 1
    return True


def parse_strings_file(path, problems):
    entries = []
    seen = set()
    in_block_comment = False

    with open(path, encoding="utf-8") as handle:
        for lineno, raw in enumerate(handle, 1):
            line = raw.strip()

            if in_block_comment:
                if "*/" in line:
                    line = line.split("*/", 1)[1].strip()
                    in_block_comment = False
                else:
                    continue

            if not line or line.startswith("//"):
                continue

            if line.startswith("/*"):
                if "*/" in line:
                    line = line.split("*/", 1)[1].strip()
                    if not line:
                        continue
                else:
                    in_block_comment = True
                    continue

            match = ENTRY_RE.match(line)
            if not match:
                problems.append(f"{path}:{lineno}: could not parse: {line}")
                continue

            key, value = match.group(1), match.group(2)

            if not c_string_is_balanced(value):
                problems.append(
                    f"{path}:{lineno}: broken escaping in {key!r} "
                    "(unescaped quote or trailing backslash)"
                )
                continue

            if key in seen:
                problems.append(f"{path}:{lineno}: duplicate key {key!r}")
                continue

            seen.add(key)
            entries.append((key, value))

    return entries


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", default=DEFAULT_BUNDLE)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="exit non-zero if any line fails to parse, so CI fails here "
        "instead of inside the generated header",
    )
    args = parser.parse_args()

    bundle_path = args.bundle
    output_path = args.output

    if not os.path.isdir(bundle_path):
        raise SystemExit(f"Bundle not found: {bundle_path}")

    lprojs = sorted(d for d in os.listdir(bundle_path) if d.endswith(".lproj"))

    problems = []
    counts = {}
    out = [
        "// Generated by generate_langs.py. Do not edit by hand.\n",
        "#import <Foundation/Foundation.h>\n\n",
        "static inline NSDictionary *GetAllTranslations(NSString *code) {\n",
    ]

    for lproj in lprojs:
        code = lproj[: -len(".lproj")]
        strings_path = os.path.join(bundle_path, lproj, "Localizable.strings")
        if not os.path.isfile(strings_path):
            problems.append(f"{strings_path}: missing Localizable.strings")
            continue

        entries = parse_strings_file(strings_path, problems)
        counts[code] = len(entries)

        out.append(f'    if ([code isEqualToString:@"{code}"]) {{\n')
        out.append("        return @{\n")
        for key, value in entries:
            # Written through as parsed: .strings escapes are already valid
            # Objective-C escapes, and re-escaping is what broke the build.
            out.append(f'            @"{key}": @"{value}",\n')
        out.append("        };\n")
        out.append("    }\n")

    out.append("    return nil;\n}\n")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write("".join(out))

    print(f"Wrote {output_path} ({len(counts)} languages)")
    for code in sorted(counts):
        print(f"  {code}: {counts[code]} keys")

    if problems:
        print("\nWarnings:", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        if args.strict:
            print(
                f"\n{len(problems)} problem(s) found and --strict was given.",
                file=sys.stderr,
            )
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
